# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# ===================================================================

# ===================================================================
# Application properties
# ===================================================================
application:
  super-role-name: Super Admin
  policy-full-access: Full Access
#  super-account-username: super

# ===================================================================
# Spring properties
# ===================================================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authorize_demo?useSSL=false
    username: root
    password: 12345678

  # JPA configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        format_sql: true
        type: trace
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  # Flyway configuration
  flyway:
    locations: classpath:/db/migration
    table: flyway_history

# ===================================================================
# Logger
# ===================================================================
logging:
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
